
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "master", "main", "development", "**" ]
  pull_request:
    branches: [ "master", "main", "development" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x
          9.x
    - name: Show dotnet version
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes
    - name: Build with dotnet
      run: dotnet build ./src/Mapster.sln
    - name: Run tests on .NET 9.0
      run: dotnet test --verbosity normal ./src/Mapster.sln
